# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:49:33,683] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:53:07,818] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:54:00,362] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:54:42,074] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:55:49,212] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 13:57:03,404] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:08:57,627] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:10:00,768] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:11:20,184] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:18:52,231] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:20:01,675] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:24:38,402] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:26:03,799] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:38:04,839] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:42:21,357] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:47:19,783] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:52:50,393] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 14:54:22,885] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 15:03:45,058] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 68, in get_events_urls
    more_event = driver.find_element_by_css_selector('a.event__more')
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.event__more"}
  (Session info: headless chrome=84.0.4147.89)

# ERROR    events_urls_parse.py[LINE:99][2020-07-23 15:06:15,936] 
receive or record error
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 92, in main
    get_events_urls(champ_url + 'results/'))
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/events_urls_parse.py", line 65, in get_events_urls
    driver.get(champoinate_url)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=84.0.4147.89)

# ERROR    ng_stat_parse.py[LINE:128][2020-07-24 14:08:50,645] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 123, in get_stat
    detail_url = soup.select('li#menu1 a')['href']
TypeError: list indices must be integers or slices, not str
# ERROR    ng_stat_parse.py[LINE:128][2020-07-24 14:09:21,124] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 123, in get_stat
    detail_url = soup.select('li#menu1 a')['href']
TypeError: list indices must be integers or slices, not str
# ERROR    ng_stat_parse.py[LINE:129][2020-07-24 14:09:49,485] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 123, in get_stat
    detail_url = soup.select('li#menu1 a')['href']
TypeError: list indices must be integers or slices, not str
# ERROR    ng_stat_parse.py[LINE:124][2020-07-24 16:16:38,839] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 115, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 60, in select_stat_in_HT
    print(keys)
UnboundLocalError: local variable 'keys' referenced before assignment
# ERROR    ng_stat_parse.py[LINE:124][2020-07-24 16:16:47,960] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 115, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 60, in select_stat_in_HT
    print(keys)
UnboundLocalError: local variable 'keys' referenced before assignment
# ERROR    ng_stat_parse.py[LINE:126][2020-07-24 16:18:14,541] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 117, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 62, in select_stat_in_HT
    print(keys)
UnboundLocalError: local variable 'keys' referenced before assignment
# ERROR    ng_stat_parse.py[LINE:127][2020-07-24 16:30:30,318] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 118, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 62, in select_stat_in_HT
    empty_stats = [{key: None} for key, value in keys]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 62, in <listcomp>
    empty_stats = [{key: None} for key, value in keys]
ValueError: too many values to unpack (expected 2)
# ERROR    ng_stat_parse.py[LINE:128][2020-07-24 16:31:22,789] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 119, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 62, in select_stat_in_HT
    empty_stats = [{key: None} for key, value in keys]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 62, in <listcomp>
    empty_stats = [{key: None} for key, value in keys]
ValueError: too many values to unpack (expected 2)
# ERROR    ng_stat_parse.py[LINE:134][2020-07-24 16:39:07,327] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 125, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in select_stat_in_HT
    empty_stats = [{key: None} for key, value in keys]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in <listcomp>
    empty_stats = [{key: None} for key, value in keys]
ValueError: too many values to unpack (expected 2)
# ERROR    ng_stat_parse.py[LINE:134][2020-07-24 16:39:29,598] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 125, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in select_stat_in_HT
    empty_stats = [{key: None} for key, value in keys]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in <listcomp>
    empty_stats = [{key: None} for key, value in keys]
ValueError: too many values to unpack (expected 2)
# ERROR    ng_stat_parse.py[LINE:134][2020-07-24 16:41:03,537] Error received stats in table data
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 125, in get_stat
    for stat in select_stat_in_HT(HDA_stat, '1x2')]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in select_stat_in_HT
    empty_stats = [{key: None} for key, value in keys]
  File "/home/max/Projects/football-stat-scraper/foot_stat_scraper/ng_stat_parse.py", line 68, in <listcomp>
    empty_stats = [{key: None} for key, value in keys]
ValueError: too many values to unpack (expected 2)
