ERROR    fs_past_stat_parser.py[LINE:127 2020-08-04 15:57-09][ForkPoolWorker-5][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 125, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:127 2020-08-04 15:57-13][ForkPoolWorker-10][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 125, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:127 2020-08-04 16:04-23][ForkPoolWorker-20][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 125, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:127 2020-08-04 16:04-26][ForkPoolWorker-15][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 125, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

