singlethreading important errors:

ERROR    fs_live_stat_parser.py[LINE:90][get_main_stat] Error receiving main stat elements https://www.flashscore.com/match/xfTkwU6A
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 77, in get_main_stat
    main_stat['round_num'] = championate_info.split(
IndexError: list index out of range
ERROR    fs_live_stat_parser.py[LINE:90][get_main_stat] Error receiving main stat elements https://www.flashscore.com/match/xfTkwU6A
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 77, in get_main_stat
    main_stat['round_num'] = championate_info.split(
IndexError: list index out of range
ERROR    speed_run_test.py[LINE:43][run_parse] ERROR RUN PARSE ON URL https://www.flashscore.com/match/xfTkwU6A
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/tests/speed_run_test.py", line 40, in run_parse
    summary_stat.update(get_past_stat(url))
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 146, in get_past_stat
    home_prev_events = find_previous_events(home_command_url, main_stat['date'])
KeyError: 'date'